apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  # $ echo -n "AKIAIOAFBVCAFGVCAFGCA" | base64
  aws-access-key-id: XXXXXXXXXXXXXXXXXXXXXXXXXX
  # $ echo -n "wJalrXUtnFEMI/K7MDENG/bAHAGHAGHAG=" | base64
  aws-secret-access-key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
