apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  # $ echo -n "AKIAIOSFODNN7EXAMPLE" | base64
  aws-access-key-id: UR AWS ID
  # $ echo -n "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" | base64
  aws-secret-access-key: UR AWS KEY
