apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f 1.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  ports:
  - name: "ui"
    port: 8081
    targetPort: 8081
  - name: "pv"
    port: 8083
    targetPort: 8083
  - name: "proxy"
    port: 8084
    targetPort: 8084
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30091
    name: ui
  - port: 8083
    nodePort: 30092
    name: pv
  - port: 8084
    nodePort: 30093
    name: proxy
  selector:
    io.kompose.service: nexus
status:
  loadBalancer: {}
