apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kafka","component":"zookeeper"},"name":"zoo","namespace":"vin"},"spec":{"clusterIP":"None","ports":[{"name":"peer","port":2888},{"name":"leader-election","port":3888}],"selector":{"app":"kafka","component":"zookeeper"}}}
  creationTimestamp: null
  labels:
    app: kafka
    component: zookeeper
  name: zoo
  selfLink: /api/v1/namespaces/vin/services/zoo
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: kafka
    component: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
