apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kafka","component":"kafka-broker"},"name":"broker","namespace":"vin"},"spec":{"clusterIP":"None","ports":[{"port":9092}],"selector":{"app":"kafka","component":"kafka-broker"}}}
  creationTimestamp: null
  labels:
    app: kafka
    component: kafka-broker
  name: broker
  selfLink: /api/v1/namespaces/vin/services/broker
spec:
  clusterIP: None
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    component: kafka-broker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
