apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"kafka","component":"kafka-broker"},"name":"kafka","namespace":"vin"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"kafka"}},"serviceName":"broker","template":{"metadata":{"annotations":null,"labels":{"app":"kafka","component":"kafka-broker"}},"spec":{"containers":[{"command":["sh","-exc","unset KAFKA_PORT \u0026\u0026 export KAFKA_BROKER_ID=${HOSTNAME##*-} \u0026\u0026 \\\nexport KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) \u0026\u0026 \\\nexec /etc/confluent/docker/run\n"],"env":[{"name":"POD_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}},{"name":"HOST_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.hostIP"}}},{"name":"KAFKA_ADVERTISED_LISTENERS","value":"EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))"},{"name":"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP","value":"PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"},{"name":"KAFKA_ZOOKEEPER_CONNECT","value":"zoo"},{"name":"KAFKA_LOG_DIRS","value":"/var/lib/kafka/data"},{"name":"KAFKA_OPTS","value":"-javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=5555:/opt/prometheus/conf/prometheus-config.yml"}],"image":"kubernautslabs/cp-kafka:5.0.0","name":"broker","ports":[{"containerPort":9092,"name":"kafka"},{"containerPort":5555,"name":"prometheus"}]}],"terminationGracePeriodSeconds":10}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: kafka
    component: kafka-broker
  name: kafka
  selfLink: /apis/apps/v1/namespaces/vin/statefulsets/kafka
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: broker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
        component: kafka-broker
    spec:
      containers:
      - command:
        - sh
        - -exc
        - |
          unset KAFKA_PORT && export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) && \
          exec /etc/confluent/docker/run
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: KAFKA_ADVERTISED_LISTENERS
          value: EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OPTS
          value: -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=5555:/opt/prometheus/conf/prometheus-config.yml
        image: kubernautslabs/cp-kafka:5.0.0
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 9092
          name: kafka
          protocol: TCP
        - containerPort: 5555
          name: prometheus
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  replicas: 0
