apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"efs-provisioner","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"efs-provisioner"}},"spec":{"containers":[{"env":[{"name":"FILE_SYSTEM_ID","valueFrom":{"configMapKeyRef":{"key":"file.system.id","name":"efs-provisioner"}}},{"name":"AWS_REGION","valueFrom":{"configMapKeyRef":{"key":"aws.region","name":"efs-provisioner"}}},{"name":"DNS_NAME","valueFrom":{"configMapKeyRef":{"key":"dns.name","name":"efs-provisioner","optional":true}}},{"name":"PROVISIONER_NAME","valueFrom":{"configMapKeyRef":{"key":"provisioner.name","name":"efs-provisioner"}}},{"name":"AWS_ACCESS_KEY_ID","value":"AKIAJRCMHWXDUOWLJ4QA"},{"name":"AWS_SECRET_ACCESS_KEY","value":"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"}],"image":"quay.io/external_storage/efs-provisioner:latest","name":"efs-provisioner","volumeMounts":[{"mountPath":"/persistentvolumes","name":"pv-volume"}]}],"serviceAccount":"efs-provisioner","volumes":[{"name":"pv-volume","nfs":{"path":"/","server":"fs-d23cf730.efs.us-east-1.amazonaws.com"}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: efs-provisioner
  name: efs-provisioner
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/efs-provisioner
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: efs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: efs-provisioner
    spec:
      containers:
      - env:
        - name: FILE_SYSTEM_ID
          valueFrom:
            configMapKeyRef:
              key: file.system.id
              name: efs-provisioner
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: aws.region
              name: efs-provisioner
        - name: DNS_NAME
          valueFrom:
            configMapKeyRef:
              key: dns.name
              name: efs-provisioner
              optional: true
        - name: PROVISIONER_NAME
          valueFrom:
            configMapKeyRef:
              key: provisioner.name
              name: efs-provisioner
        - name: AWS_ACCESS_KEY_ID
          value: AKIAJRCMHWXDUOWLJ4QA
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        image: quay.io/external_storage/efs-provisioner:latest
        imagePullPolicy: Always
        name: efs-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: pv-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: efs-provisioner
      serviceAccountName: efs-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pv-volume
        nfs:
          path: /
          server: fs-d23cf730.efs.us-east-1.amazonaws.com
status: {}
