apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"aws-efs"},"name":"efs","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Mi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: aws-efs
    volume.beta.kubernetes.io/storage-provisioner: example.com/aws-efs
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: efs
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/efs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  volumeName: pvc-0101eceb-d918-11e9-b41b-12b826d43e9a
status: {}
