apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
spec:
  replicas: 1
  selector:
   matchLabels:
     app: httpd
  template:
    metadata:
    labels:
      app: httpd
    spec:
      containers:
      - name: httpd
      image: httpd:latest
      ports:
      - containerPort: 80
