apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f 1.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "50000"
    port: 50000
    targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
