apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"monitoring-influxdb","namespace":"kube-system"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"k8s-app":"influxdb","task":"monitoring"}},"spec":{"containers":[{"image":"k8s.gcr.io/heapster-influxdb-amd64:v1.5.2","name":"influxdb","volumeMounts":[{"mountPath":"/data","name":"influxdb-storage"}]}],"volumes":[{"emptyDir":{},"name":"influxdb-storage"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: influxdb
    task: monitoring
  name: monitoring-influxdb
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-influxdb
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      k8s-app: influxdb
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: influxdb
        task: monitoring
    spec:
      containers:
      - image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
        imagePullPolicy: IfNotPresent
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: influxdb-storage
status: {}
