apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"digitized-db","namespace":"commonpipeline"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"digitized-db"}},"template":{"metadata":{"labels":{"run":"digitized-db"}},"spec":{"containers":[{"image":"mongo","name":"digitized-db","volumeMounts":[{"mountPath":"/data/db","name":"digitized-db","subPath":"commonpipeline/digitized-db"}]}],"imagePullSecrets":[{"name":"aws-registry"}],"volumes":[{"name":"digitized-db","persistentVolumeClaim":{"claimName":"commonpipeline"}}]}}}}
  creationTimestamp: null
  generation: 1
  name: digitized-db
  selfLink: /apis/extensions/v1beta1/namespaces/commonpipeline/deployments/digitized-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: digitized-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: digitized-db
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: digitized-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: digitized-db
          subPath: commonpipeline/digitized-db
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: digitized-db
        persistentVolumeClaim:
          claimName: commonpipeline
status: {}
