apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"usermanagement-contract-abstraction-dev","namespace":"commonpipeline"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"usermanagement-contract-abstraction-dev","tier":"backend"}},"template":{"metadata":{"labels":{"run":"usermanagement-contract-abstraction-dev","tier":"backend"}},"spec":{"containers":[{"env":[{"name":"allowed_origins","value":"http://10.235.112.135:4200,http://localhost:4400,http://localhost:4200,http://10.235.112.135:8032"},{"name":"content_origins","value":"http://10.235.112.135:4200"},{"name":"enable_ldap","value":"false"},{"name":"ldap_domain_name","value":"wipro.com"},{"name":"ldap_url","value":"ldap://pne-hjn-dc05.wipro.com:389/"}],"image":"091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:usermanagement_contract-abstraction-dev","imagePullPolicy":"Always","name":"usermanagement-contract-abstraction-dev"}],"imagePullSecrets":[{"name":"aws-registry"}]}}}}
  creationTimestamp: null
  generation: 1
  name: usermanagement-contract-abstraction-dev
  selfLink: /apis/extensions/v1beta1/namespaces/commonpipeline/deployments/usermanagement-contract-abstraction-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: usermanagement-contract-abstraction-dev
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: usermanagement-contract-abstraction-dev
        tier: backend
    spec:
      containers:
      - env:
        - name: allowed_origins
          value: http://10.235.112.135:4200,http://localhost:4400,http://localhost:4200,http://10.235.112.135:8032
        - name: content_origins
          value: http://10.235.112.135:4200
        - name: enable_ldap
          value: "false"
        - name: ldap_domain_name
          value: wipro.com
        - name: ldap_url
          value: ldap://pne-hjn-dc05.wipro.com:389/
        image: 091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:usermanagement_contract-abstraction-dev
        imagePullPolicy: Always
        name: usermanagement-contract-abstraction-dev
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
