apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"cp-process-statistics-mlops","namespace":"commonpipeline"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"cp-process-statistics-mlops","tier":"backend"}},"template":{"metadata":{"labels":{"run":"cp-process-statistics-mlops","tier":"backend"}},"spec":{"containers":[{"image":"091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:cp-process-statistics-mlops","imagePullPolicy":"Always","name":"cp-process-statistics-mlops"}],"imagePullSecrets":[{"name":"aws-registry"}]}}}}
  creationTimestamp: null
  generation: 1
  name: cp-process-statistics-mlops
  selfLink: /apis/extensions/v1beta1/namespaces/commonpipeline/deployments/cp-process-statistics-mlops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cp-process-statistics-mlops
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cp-process-statistics-mlops
        tier: backend
    spec:
      containers:
      - image: 091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:cp-process-statistics-mlops
        imagePullPolicy: Always
        name: cp-process-statistics-mlops
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
