apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"dc-form-extraction","namespace":"commonpipeline"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"dc-form-extraction","tier":"backend"}},"template":{"metadata":{"labels":{"run":"dc-form-extraction","tier":"backend"}},"spec":{"containers":[{"image":"091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:commonpipeline-dc-form-extraction","imagePullPolicy":"Always","name":"dc-form-extraction","volumeMounts":[{"mountPath":"/Holmes","name":"commonpipeline","subPath":"commonpipeline/Holmes"}]}],"imagePullSecrets":[{"name":"aws-registry"}],"volumes":[{"name":"commonpipeline","persistentVolumeClaim":{"claimName":"commonpipeline"}}]}}}}
  creationTimestamp: null
  generation: 1
  name: dc-form-extraction
  selfLink: /apis/extensions/v1beta1/namespaces/commonpipeline/deployments/dc-form-extraction
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: dc-form-extraction
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dc-form-extraction
        tier: backend
    spec:
      containers:
      - image: 091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:commonpipeline-dc-form-extraction
        imagePullPolicy: Always
        name: dc-form-extraction
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /Holmes
          name: commonpipeline
          subPath: commonpipeline/Holmes
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: commonpipeline
        persistentVolumeClaim:
          claimName: commonpipeline
status: {}
