apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"configurationdetails","namespace":"commonpipeline"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"configurationdetails","tier":"backend"}},"template":{"metadata":{"labels":{"run":"configurationdetails","tier":"backend"}},"spec":{"containers":[{"image":"091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:commonpipeline_dev_configurationdetails","imagePullPolicy":"Always","name":"configurationdetails","volumeMounts":[{"mountPath":"/GA","name":"commonpipeline","subPath":"commonpipeline/GAV3-DC"}]}],"imagePullSecrets":[{"name":"aws-registry"}],"volumes":[{"name":"commonpipeline","persistentVolumeClaim":{"claimName":"commonpipeline"}}]}}}}
  creationTimestamp: null
  generation: 1
  name: configurationdetails
  selfLink: /apis/extensions/v1beta1/namespaces/commonpipeline/deployments/configurationdetails
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: configurationdetails
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: configurationdetails
        tier: backend
    spec:
      containers:
      - image: 091307694858.dkr.ecr.us-west-2.amazonaws.com/commonpipeline:commonpipeline_dev_configurationdetails
        imagePullPolicy: Always
        name: configurationdetails
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /GA
          name: commonpipeline
          subPath: commonpipeline/GAV3-DC
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: commonpipeline
        persistentVolumeClaim:
          claimName: commonpipeline
status: {}
