apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"sop-automation","tier":"backend"},"name":"sop-automation","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"sop-automation","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: sop-automation
    tier: backend
  name: sop-automation
  selfLink: /api/v1/namespaces/commonpipeline/services/sop-automation
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: sop-automation
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
