apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"traininginitiator","tier":"backend"},"name":"traininginitiator","namespace":"commonpipeline"},"spec":{"ports":[{"port":8023,"protocol":"TCP"}],"selector":{"run":"traininginitiator","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: traininginitiator
    tier: backend
  name: traininginitiator
  selfLink: /api/v1/namespaces/commonpipeline/services/traininginitiator
spec:
  ports:
  - port: 8023
    protocol: TCP
    targetPort: 8023
  selector:
    run: traininginitiator
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
