apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"sftp","tier":"backend"},"name":"sftp","namespace":"commonpipeline"},"spec":{"ports":[{"port":2222,"protocol":"TCP","targetPort":22}],"selector":{"run":"sftp","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: sftp
    tier: backend
  name: sftp
  selfLink: /api/v1/namespaces/commonpipeline/services/sftp
spec:
  ports:
  - port: 2222
    protocol: TCP
    targetPort: 22
  selector:
    run: sftp
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
