apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"ftr-extraction-service","tier":"backend"},"name":"ftr-extraction-service","namespace":"commonpipeline"},"spec":{"ports":[{"port":8040,"protocol":"TCP"}],"selector":{"run":"ftr-extraction-service","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: ftr-extraction-service
    tier: backend
  name: ftr-extraction-service
  selfLink: /api/v1/namespaces/commonpipeline/services/ftr-extraction-service
spec:
  ports:
  - port: 8040
    protocol: TCP
    targetPort: 8040
  selector:
    run: ftr-extraction-service
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
