apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"studio-notifier-service","tier":"backend"},"name":"studio-notifier-service","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"studio-notifier-service","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: studio-notifier-service
    tier: backend
  name: studio-notifier-service
  selfLink: /api/v1/namespaces/commonpipeline/services/studio-notifier-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: studio-notifier-service
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
