apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"pdf-to-html","tier":"backend"},"name":"pdf-to-html","namespace":"commonpipeline"},"spec":{"ports":[{"port":5001,"protocol":"TCP"}],"selector":{"run":"pdf-to-html","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: pdf-to-html
    tier: backend
  name: pdf-to-html
  selfLink: /api/v1/namespaces/commonpipeline/services/pdf-to-html
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    run: pdf-to-html
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
