apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"dvs-garnish-ui","tier":"backend"},"name":"dvs-garnish-ui","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"dvs-garnish-ui","tier":"backend"},"type":"NodePort"}}
  creationTimestamp: null
  labels:
    run: dvs-garnish-ui
    tier: backend
  name: dvs-garnish-ui
  selfLink: /api/v1/namespaces/commonpipeline/services/dvs-garnish-ui
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: dvs-garnish-ui
    tier: backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
