apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"operational-db","tier":"backend"},"name":"operational-db","namespace":"commonpipeline"},"spec":{"ports":[{"port":27017,"protocol":"TCP"}],"selector":{"run":"operational-db","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: operational-db
    tier: backend
  name: operational-db
  selfLink: /api/v1/namespaces/commonpipeline/services/operational-db
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: operational-db
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
