apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"usermanagement-contract-abstraction-dev","tier":"backend"},"name":"usermanagement-contract-abstraction-dev","namespace":"commonpipeline"},"spec":{"ports":[{"port":8021,"protocol":"TCP"}],"selector":{"run":"usermanagement-contract-abstraction-dev","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: usermanagement-contract-abstraction-dev
    tier: backend
  name: usermanagement-contract-abstraction-dev
  selfLink: /api/v1/namespaces/commonpipeline/services/usermanagement-contract-abstraction-dev
spec:
  ports:
  - port: 8021
    protocol: TCP
    targetPort: 8021
  selector:
    run: usermanagement-contract-abstraction-dev
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
