apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"dc-form-extraction","tier":"backend"},"name":"dc-form-extraction","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"dc-form-extraction","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: dc-form-extraction
    tier: backend
  name: dc-form-extraction
  selfLink: /api/v1/namespaces/commonpipeline/services/dc-form-extraction
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: dc-form-extraction
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
