apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"it-ops-ui","run":"it-ops-ui","tier":"backend"},"name":"it-ops-ui-lb","namespace":"commonpipeline"},"spec":{"ports":[{"name":"it-ops-ui-lb","port":443,"protocol":"TCP","targetPort":4200}],"selector":{"app":"it-ops-ui","run":"it-ops-ui","tier":"backend"},"type":"LoadBalancer"}}
  creationTimestamp: null
  labels:
    app: it-ops-ui
    run: it-ops-ui
    tier: backend
  name: it-ops-ui-lb
  selfLink: /api/v1/namespaces/commonpipeline/services/it-ops-ui-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: it-ops-ui-lb
    nodePort: 32686
    port: 443
    protocol: TCP
    targetPort: 4200
  selector:
    app: it-ops-ui
    run: it-ops-ui
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
