apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"document-type-identifier","tier":"backend"},"name":"document-type-identifier","namespace":"commonpipeline"},"spec":{"ports":[{"port":8895,"protocol":"TCP"}],"selector":{"run":"document-type-identifier"}}}
  creationTimestamp: null
  labels:
    run: document-type-identifier
    tier: backend
  name: document-type-identifier
  selfLink: /api/v1/namespaces/commonpipeline/services/document-type-identifier
spec:
  ports:
  - port: 8895
    protocol: TCP
    targetPort: 8895
  selector:
    run: document-type-identifier
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
