apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"cp-dvs-ui","tier":"backend"},"name":"cp-dvs-ui","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"cp-dvs-ui","tier":"backend"},"type":"NodePort"}}
  creationTimestamp: null
  labels:
    run: cp-dvs-ui
    tier: backend
  name: cp-dvs-ui
  selfLink: /api/v1/namespaces/commonpipeline/services/cp-dvs-ui
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: cp-dvs-ui
    tier: backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
