apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"rulesvalidator","tier":"backend"},"name":"rulesvalidator","namespace":"commonpipeline"},"spec":{"ports":[{"port":8083,"protocol":"TCP"}],"selector":{"run":"rulesvalidator","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: rulesvalidator
    tier: backend
  name: rulesvalidator
  selfLink: /api/v1/namespaces/commonpipeline/services/rulesvalidator
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    run: rulesvalidator
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
