apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"dcformsprocessingwrapper","tier":"backend"},"name":"dcformsprocessingwrapper","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"dcformsprocessingwrapper","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: dcformsprocessingwrapper
    tier: backend
  name: dcformsprocessingwrapper
  selfLink: /api/v1/namespaces/commonpipeline/services/dcformsprocessingwrapper
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: dcformsprocessingwrapper
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
