apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"config-db"},"name":"config-db-lb","namespace":"commonpipeline"},"spec":{"ports":[{"name":"config-db-lb","port":27017,"protocol":"TCP","targetPort":27017}],"selector":{"run":"config-db"},"type":"NodePort"}}
  creationTimestamp: null
  labels:
    run: config-db
  name: config-db-lb
  selfLink: /api/v1/namespaces/commonpipeline/services/config-db-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: config-db-lb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: config-db
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
