apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"ca-dvs-ui","tier":"backend"},"name":"ca-dvs-ui","namespace":"commonpipeline"},"spec":{"ports":[{"port":4200,"protocol":"TCP"}],"selector":{"run":"ca-dvs-ui","tier":"backend"},"type":"NodePort"}}
  creationTimestamp: null
  labels:
    run: ca-dvs-ui
    tier: backend
  name: ca-dvs-ui
  selfLink: /api/v1/namespaces/commonpipeline/services/ca-dvs-ui
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    run: ca-dvs-ui
    tier: backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
