apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"dl-attribute-extractor","tier":"backend"},"name":"dl-attribute-extractor","namespace":"commonpipeline"},"spec":{"ports":[{"port":8020,"protocol":"TCP"}],"selector":{"run":"dl-attribute-extractor","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: dl-attribute-extractor
    tier: backend
  name: dl-attribute-extractor
  selfLink: /api/v1/namespaces/commonpipeline/services/dl-attribute-extractor
spec:
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 8020
  selector:
    run: dl-attribute-extractor
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
