apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"lease-attribute-extractor","tier":"backend"},"name":"lease-attribute-extractor","namespace":"commonpipeline"},"spec":{"ports":[{"port":8005,"protocol":"TCP"}],"selector":{"run":"lease-attribute-extractor","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: lease-attribute-extractor
    tier: backend
  name: lease-attribute-extractor
  selfLink: /api/v1/namespaces/commonpipeline/services/lease-attribute-extractor
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    run: lease-attribute-extractor
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
