apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"dcstartprocessingdocs","tier":"backend"},"name":"dcstartprocessingdocs","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"dcstartprocessingdocs","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: dcstartprocessingdocs
    tier: backend
  name: dcstartprocessingdocs
  selfLink: /api/v1/namespaces/commonpipeline/services/dcstartprocessingdocs
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: dcstartprocessingdocs
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
