apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"portaldao","tier":"backend"},"name":"portaldao","namespace":"commonpipeline"},"spec":{"ports":[{"port":8022,"protocol":"TCP"}],"selector":{"run":"portaldao","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: portaldao
    tier: backend
  name: portaldao
  selfLink: /api/v1/namespaces/commonpipeline/services/portaldao
spec:
  ports:
  - port: 8022
    protocol: TCP
    targetPort: 8022
  selector:
    run: portaldao
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
