apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"user-management","tier":"backend"},"name":"user-management","namespace":"commonpipeline"},"spec":{"ports":[{"port":8021,"protocol":"TCP"}],"selector":{"run":"user-management","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: user-management
    tier: backend
  name: user-management
  selfLink: /api/v1/namespaces/commonpipeline/services/user-management
spec:
  ports:
  - port: 8021
    protocol: TCP
    targetPort: 8021
  selector:
    run: user-management
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
