apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"it-ops-dao","tier":"backend"},"name":"it-ops-dao","namespace":"commonpipeline"},"spec":{"ports":[{"port":8080,"protocol":"TCP"}],"selector":{"run":"it-ops-dao","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: it-ops-dao
    tier: backend
  name: it-ops-dao
  selfLink: /api/v1/namespaces/commonpipeline/services/it-ops-dao
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: it-ops-dao
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
