apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"orch-attr-extractor","tier":"backend"},"name":"orch-attr-extractor","namespace":"commonpipeline"},"spec":{"ports":[{"port":5001,"protocol":"TCP"}],"selector":{"run":"orch-attr-extractor","tier":"backend"}}}
  creationTimestamp: null
  labels:
    run: orch-attr-extractor
    tier: backend
  name: orch-attr-extractor
  selfLink: /api/v1/namespaces/commonpipeline/services/orch-attr-extractor
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    run: orch-attr-extractor
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
