apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"config-db"},"name":"config-db","namespace":"commonpipeline"},"spec":{"ports":[{"port":27017,"protocol":"TCP"}],"selector":{"run":"config-db"}}}
  creationTimestamp: null
  labels:
    run: config-db
  name: config-db
  selfLink: /api/v1/namespaces/commonpipeline/services/config-db
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: config-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
