apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"kafka","component":"zookeeper"},"name":"zoo","namespace":"commonpipeline"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"kafka","component":"zookeeper"}},"serviceName":"zoo","template":{"metadata":{"labels":{"app":"kafka","component":"zookeeper"}},"spec":{"containers":[{"command":["/bin/bash","-c","export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1)) \u0026\u0026 /etc/confluent/docker/run"],"env":[{"name":"ZOOKEEPER_CLIENT_PORT","value":"2181"},{"name":"ZOOKEEPER_SERVER_ID","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"ZOOKEEPER_SERVERS","value":"zoo-0.zoo.commonpipeline.svc.cluster.local:2888:3888;zoo-1.zoo.commonpipeline.svc.cluster.local:2888:3888;zoo-2.zoo.commonpipeline.svc.cluster.local:2888:3888"}],"image":"confluentinc/cp-zookeeper:5.0.0","name":"zookeeper","ports":[{"containerPort":2181,"name":"client"},{"containerPort":2888,"name":"peer"},{"containerPort":3888,"name":"leader-election"}]}],"terminationGracePeriodSeconds":10}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: kafka
    component: zookeeper
  name: zoo
  selfLink: /apis/apps/v1/namespaces/commonpipeline/statefulsets/zoo
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
      component: zookeeper
  serviceName: zoo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
        component: zookeeper
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1)) && /etc/confluent/docker/run
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ZOOKEEPER_SERVERS
          value: zoo-0.zoo.commonpipeline.svc.cluster.local:2888:3888;zoo-1.zoo.commonpipeline.svc.cluster.local:2888:3888;zoo-2.zoo.commonpipeline.svc.cluster.local:2888:3888
        image: confluentinc/cp-zookeeper:5.0.0
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: peer
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  replicas: 0
