apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"kafka","component":"kafka-broker"},"name":"kafka","namespace":"commonpipeline"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"kafka"}},"serviceName":"broker","template":{"metadata":{"labels":{"app":"kafka","component":"kafka-broker"}},"spec":{"containers":[{"command":["sh","-exc","unset KAFKA_PORT \u0026\u0026 export KAFKA_BROKER_ID=${HOSTNAME##*-} \u0026\u0026 \\\nexport KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) \u0026\u0026 \\\nexec /etc/confluent/docker/run\n"],"env":[{"name":"POD_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}},{"name":"HOST_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.hostIP"}}},{"name":"KAFKA_ADVERTISED_LISTENERS","value":"EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))"},{"name":"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP","value":"PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"},{"name":"KAFKA_ZOOKEEPER_CONNECT","value":"zoo"}],"image":"kubernautslabs/cp-kafka:5.0.0","name":"broker","ports":[{"containerPort":9092,"name":"kafka"}]}],"terminationGracePeriodSeconds":10}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: kafka
    component: kafka-broker
  name: kafka
  selfLink: /apis/apps/v1/namespaces/commonpipeline/statefulsets/kafka
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: broker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
        component: kafka-broker
    spec:
      containers:
      - command:
        - sh
        - -exc
        - |
          unset KAFKA_PORT && export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) && \
          exec /etc/confluent/docker/run
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: KAFKA_ADVERTISED_LISTENERS
          value: EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo
        image: kubernautslabs/cp-kafka:5.0.0
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 9092
          name: kafka
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  replicas: 0
