apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
data:
  aws-access-key-id: XXXXXXXXXXXXXXXXXXX   Secrets need to be converted to base64. Eg:  echo -n 'AMJZ7XOS5QSYJKIAJ5Q4' | base64
  aws-secret-access-key: xxxxxxxxxxxxx Secrets need to be converted to base64. Eg:  echo -n 'AMJZ7XOS5QSYJKIAJ5Q4' | base64

