apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: aws-secrets
  selfLink: /apis/batch/v1beta1/namespaces/infrastructure/cronjobs/aws-secrets
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 4
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /run.sh
            env:
            - name: AWS_ACCOUNT
              value: "091307694858"
            - name: AWS_REGION
              value: us-east-1
            - name: NAMESPACES
              value: infrastructure default
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws-access-key-id
                  name: aws-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws-secret-access-key
                  name: aws-secrets
            image: frekele/aws-ecr-kubectl:stable
            imagePullPolicy: Always
            name: aws-secrets
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: ecr-update-service-account
          serviceAccountName: ecr-update-service-account
          terminationGracePeriodSeconds: 0
  schedule: '* */6 * * *'
  successfulJobsHistoryLimit: 2
  suspend: false
status: {}
