apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    controller-uid: 4c4554de-e5ab-11e9-b41b-12b826d43e9a
    job-name: aws-secrets-1570085940
  name: aws-secrets-1570085940
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: aws-secrets
    uid: 6f5d5979-d91f-11e9-9a31-02c30502db02
  selfLink: /apis/batch/v1/namespaces/infrastructure/jobs/aws-secrets-1570085940
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 4c4554de-e5ab-11e9-b41b-12b826d43e9a
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 4c4554de-e5ab-11e9-b41b-12b826d43e9a
        job-name: aws-secrets-1570085940
    spec:
      containers:
      - command:
        - /run.sh
        env:
        - name: AWS_ACCOUNT
          value: "091307694858"
        - name: AWS_REGION
          value: us-east-1
        - name: NAMESPACES
          value: infrastructure default
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: aws-secrets
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: aws-secrets
        image: frekele/aws-ecr-kubectl:stable
        imagePullPolicy: Always
        name: aws-secrets
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ecr-update-service-account
      serviceAccountName: ecr-update-service-account
      terminationGracePeriodSeconds: 0
status: {}
