apiVersion: v1
data:
  aws-access-key-id: QUtJQUpSQ01IV1hEVU9XTEo0UUE=
  aws-secret-access-key: bFFCNnRJWW52ZldJSk5IbXkzbk5pQ1FyWC9qa3pGc3Y2R2xwTzl3Kw==
kind: Secret
metadata:
  creationTimestamp: null
  name: aws-secrets
  selfLink: /api/v1/namespaces/infrastructure/secrets/aws-secrets
type: Opaque
